import 'package:flutter/material.dart';
import 'hotel_card.dart';

class HotelList extends StatelessWidget {
   final void Function(Hotel)? onHotelTap;

   HotelList({Key? key, this.onHotelTap}) : super(key: key);

  final List<Hotel> _hotels = [
    Hotel(
      id: 'HOT001',
      name: 'Grand Paradise Resort & Spa',
      city: 'Bali, Indonesia',
      imageUrls: [
        'https://picsum.photos/800/600?random=1',
        'https://picsum.photos/800/600?random=2',
        'https://picsum.photos/800/600?random=3',
      ],
      starRating: 5.0,
      customerRating: 4.8,
      reviewCount: 1247,
      description: 'Luxurious 5-star beachfront resort with infinity pools, world-class spa, and multiple dining options overlooking the Indian Ocean.',
      startingPrice : 450.00,
      contactNumber: '+62 361 847 3333',
      amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Parking', 'Beach Access'],
      rooms: [
        Room(
          id: 'ROOM001',
          name: 'Deluxe King Room',
          description: 'Spacious room with king bed, city view, and modern amenities.',
          images: ['https://picsum.photos/800/600?random=22', 'https://picsum.photos/800/600?random=23'],
          maxGuests: 2,
          pricePerNight: 150.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM002',
          name: 'Standard Double Room',
          description: 'Comfortable room with two beds, perfect for families.',
          images: ['https://picsum.photos/800/600?random=24', 'https://picsum.photos/800/600?random=25'],
          maxGuests: 4,
          pricePerNight: 120.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM003',
          name: 'Suite with Balcony',
          description: 'Luxurious suite with private balcony and premium services.',
          images: ['https://picsum.photos/800/600?random=26', 'https://picsum.photos/800/600?random=27'],
          maxGuests: 3,
          pricePerNight: 200.0,
          isAvailable: false,
        ),
      ],
    ),
    Hotel(
      id: 'HOT002',
      name: 'Tokyo Skyline Hotel',
      city: 'Tokyo, Japan',
      imageUrls: [
        'https://picsum.photos/800/600?random=4',
        'https://picsum.photos/800/600?random=5',
      ],
      starRating: 4.5,
      customerRating: 4.6,
      reviewCount: 892,
      description: 'Modern high-rise hotel in Shibuya with panoramic city views, premium amenities, and easy access to metro stations.',
      startingPrice : 320.00,
      contactNumber: '+81 3 5459 7000',
      amenities: ['Free WiFi', 'Restaurant', 'Business Center', 'Concierge', 'Room Service', 'Laundry'],
      rooms: [
        Room(
          id: 'ROOM101',
          name: 'City View Twin Room',
          description: 'Modern room with twin beds and panoramic city views.',
          images: ['https://picsum.photos/800/600?random=28', 'https://picsum.photos/800/600?random=29'],
          maxGuests: 2,
          pricePerNight: 180.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM102',
          name: 'Executive Suite',
          description: 'Premium suite with lounge area and business facilities.',
          images: ['https://picsum.photos/800/600?random=30', 'https://picsum.photos/800/600?random=31'],
          maxGuests: 2,
          pricePerNight: 280.0,
          isAvailable: true,
        ),
      ],
    ),
    Hotel(
      id: 'HOT003',
      name: 'Parisian Heritage Hotel',
      city: 'Paris, France',
      imageUrls: [
        'https://picsum.photos/800/600?random=6',
        'https://picsum.photos/800/600?random=7',
      ],
      starRating: 4.0,
      customerRating: 4.3,
      reviewCount: 654,
      description: 'Charming boutique hotel in the Latin Quarter with antique furnishings, Eiffel Tower views, and authentic French breakfast.',
      startingPrice : 280.00,
      contactNumber: '+33 1 40 46 72 00',
      amenities: ['Free WiFi', 'Breakfast', 'Bar', 'Terrace', 'Luggage Storage', 'Tour Desk'],
      rooms: [
        Room(
          id: 'ROOM201',
          name: 'Classic Single Room',
          description: 'Cozy room with Parisian charm and period furnishings.',
          images: ['https://picsum.photos/800/600?random=32', 'https://picsum.photos/800/600?random=33'],
          maxGuests: 1,
          pricePerNight: 100.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM202',
          name: 'Deluxe Double with View',
          description: 'Room with Eiffel Tower view and luxurious amenities.',
          images: ['https://picsum.photos/800/600?random=34', 'https://picsum.photos/800/600?random=35'],
          maxGuests: 2,
          pricePerNight: 220.0,
          isAvailable: true,
        ),
      ],
    ),
    Hotel(
      id: 'HOT004',
      name: 'New York Central Plaza',
      city: 'New York, USA',
      imageUrls: [
        'https://picsum.photos/800/600?random=8',
        'https://picsum.photos/800/600?random=9',
      ],
      starRating: 4.0,
      customerRating: 4.5,
      reviewCount: 2105,
      description: 'Contemporary hotel in Manhattan with direct subway access, business facilities, and Central Park proximity.',
      startingPrice : 380.00,
      contactNumber: '+1 212-581-8100',
      amenities: ['Free WiFi', 'Fitness Center', 'Business Center', 'Restaurant', '24-hour Front Desk', 'Valet Parking'],
      rooms: [
        Room(
          id: 'ROOM301',
          name: 'Standard Room',
          description: 'Well-appointed room with city views.',
          images: ['https://picsum.photos/800/600?random=36', 'https://picsum.photos/800/600?random=37'],
          maxGuests: 2,
          pricePerNight: 200.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM302',
          name: 'Luxury Suite',
          description: 'Spacious suite with Central Park views and premium amenities.',
          images: ['https://picsum.photos/800/600?random=38', 'https://picsum.photos/800/600?random=39'],
          maxGuests: 4,
          pricePerNight: 350.0,
          isAvailable: false,
        ),
      ],
    ),
    Hotel(
      id: 'HOT005',
      name: 'Royal Garden Hotel',
      city: 'London, UK',
      imageUrls: [
        'https://picsum.photos/800/600?random=10',
        'https://picsum.photos/800/600?random=11',
      ],
      starRating: 5.0,
      customerRating: 4.9,
      reviewCount: 1876,
      description: 'Luxury hotel overlooking Kensington Gardens with afternoon tea service, fine dining restaurants, and chauffeur service.',
      startingPrice : 550.00,
      contactNumber: '+44 20 7373 8000',
      amenities: ['Free WiFi', 'Spa', 'Restaurants', 'Bar', 'Gym', 'Parking', 'Room Service', 'Concierge'],
      rooms: [
        Room(
          id: 'ROOM401',
          name: 'Garden View Room',
          description: 'Elegant room overlooking Kensington Gardens.',
          images: ['https://picsum.photos/800/600?random=40', 'https://picsum.photos/800/600?random=41'],
          maxGuests: 2,
          pricePerNight: 300.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM402',
          name: 'Royal Suite',
          description: 'Grand suite with separate living area and premium service.',
          images: ['https://picsum.photos/800/600?random=42', 'https://picsum.photos/800/600?random=43'],
          maxGuests: 4,
          pricePerNight: 500.0,
          isAvailable: true,
        ),
      ],
    ),
    Hotel(
      id: 'HOT006',
      name: 'Sydney Harbour Suites',
      city: 'Sydney, Australia',
      imageUrls: [
        'https://picsum.photos/800/600?random=12',
        'https://picsum.photos/800/600?random=13',
      ],
      starRating: 4.5,
      customerRating: 4.7,
      reviewCount: 943,
      description: 'Waterfront hotel with Opera House views, rooftop pool, and premium suites with private balconies.',
      startingPrice : 420.00,
      contactNumber: '+61 2 9256 4000',
      amenities: ['Free WiFi', 'Swimming Pool', 'Restaurant', 'Bar', 'Gym', 'Spa', 'Beach Access'],
      rooms: [
        Room(
          id: 'ROOM501',
          name: 'Opera House View Room',
          description: 'Room with stunning Opera House and Harbour views.',
          images: ['https://picsum.photos/800/600?random=44', 'https://picsum.photos/800/600?random=45'],
          maxGuests: 2,
          pricePerNight: 280.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM502',
          name: 'Penthouse Suite',
          description: 'Luxurious penthouse with private balcony and premium amenities.',
          images: ['https://picsum.photos/800/600?random=46', 'https://picsum.photos/800/600?random=47'],
          maxGuests: 3,
          pricePerNight: 450.0,
          isAvailable: false,
        ),
      ],
    ),
    Hotel(
      id: 'HOT007',
      name: 'Dubai Desert Oasis',
      city: 'Dubai, UAE',
      imageUrls: [
        'https://picsum.photos/800/600?random=14',
        'https://picsum.photos/800/600?random=15',
      ],
      starRating: 5.0,
      customerRating: 4.8,
      reviewCount: 1765,
      description: 'Ultra-luxurious desert resort with private villas, camel rides, traditional spa, and desert safari experiences.',
      startingPrice : 650.00,
      contactNumber: '+971 4 501 8888',
      amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Restaurants', 'Desert Activities', 'Private Villas', 'Butler Service'],
      rooms: [
        Room(
          id: 'ROOM601',
          name: 'Desert Villa',
          description: 'Private villa with pool and desert views.',
          images: ['https://picsum.photos/800/600?random=48', 'https://picsum.photos/800/600?random=49'],
          maxGuests: 4,
          pricePerNight: 600.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM602',
          name: 'Luxury Bedouin Suite',
          description: 'Traditional luxury suite with modern amenities.',
          images: ['https://picsum.photos/800/600?random=50', 'https://picsum.photos/800/600?random=51'],
          maxGuests: 2,
          pricePerNight: 450.0,
          isAvailable: true,
        ),
      ],
    ),
    Hotel(
      id: 'HOT008',
      name: 'Marina Bay Sands',
      city: 'Singapore',
      imageUrls: [
        'https://picsum.photos/800/600?random=16',
        'https://picsum.photos/800/600?random=17',
      ],
      starRating: 5.0,
      customerRating: 4.9,
      reviewCount: 3142,
      description: 'Iconic integrated resort with infinity pool, observation deck, casino, shopping mall, and celebrity chef restaurants.',
      startingPrice : 580.00,
      contactNumber: '+65 6688 8868',
      amenities: ['Free WiFi', 'Infinity Pool', 'Casino', 'Shopping Mall', 'Restaurants', 'Spa', 'Observation Deck'],
      rooms: [
        Room(
          id: 'ROOM701',
          name: 'Marina View Room',
          description: 'Modern room with Marina Bay views and city skyline.',
          images: ['https://picsum.photos/800/600?random=52', 'https://picsum.photos/800/600?random=53'],
          maxGuests: 2,
          pricePerNight: 350.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM702',
          name: 'Infinity Pool Suite',
          description: 'Premium suite with private access to infinity pool.',
          images: ['https://picsum.photos/800/600?random=54', 'https://picsum.photos/800/600?random=55'],
          maxGuests: 3,
          pricePerNight: 550.0,
          isAvailable: true,
        ),
      ],
    ),
    Hotel(
      id: 'HOT009',
      name: 'Bangkok Riverside Palace',
      city: 'Bangkok, Thailand',
      imageUrls: [
        'https://picsum.photos/800/600?random=18',
        'https://picsum.photos/800/600?random=19',
      ],
      starRating: 5.0,
      customerRating: 4.7,
      reviewCount: 1890,
      description: 'Traditional Thai-style hotel on Chao Phraya River with river view rooms, traditional massage, and boat shuttle service.',
      startingPrice : 290.00,
      contactNumber: '+66 2 659 9000',
      amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Restaurant', 'River View', 'Boat Shuttle', 'Cultural Shows'],
      rooms: [
        Room(
          id: 'ROOM801',
          name: 'River View Room',
          description: 'Beautiful room with Chao Phraya River views.',
          images: ['https://picsum.photos/800/600?random=56', 'https://picsum.photos/800/600?random=57'],
          maxGuests: 2,
          pricePerNight: 150.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM802',
          name: 'Thai Luxury Suite',
          description: 'Spacious suite with traditional Thai design and river view.',
          images: ['https://picsum.photos/800/600?random=58', 'https://picsum.photos/800/600?random=59'],
          maxGuests: 3,
          pricePerNight: 280.0,
          isAvailable: true,
        ),
      ],
    ),
    Hotel(
      id: 'HOT010',
      name: 'Colosseum View Hotel',
      city: 'Rome, Italy',
      imageUrls: [
        'https://picsum.photos/800/600?random=20',
        'https://picsum.photos/800/600?random=21',
      ],
      starRating: 4.0,
      customerRating: 4.4,
      reviewCount: 876,
      description: 'Historic hotel with Colosseum views, rooftop restaurant serving Italian cuisine, and walking distance to ancient sites.',
      startingPrice : 320.00,
      contactNumber: '+39 06 482 7444',
      amenities: ['Free WiFi', 'Rooftop Restaurant', 'Bar', 'Terrace', 'Tour Desk', 'Bicycle Rental'],
      rooms: [
        Room(
          id: 'ROOM901',
          name: 'Colosseum View Room',
          description: 'Historic room with direct Colosseum views.',
          images: ['https://picsum.photos/800/600?random=60', 'https://picsum.photos/800/600?random=61'],
          maxGuests: 2,
          pricePerNight: 180.0,
          isAvailable: true,
        ),
        Room(
          id: 'ROOM902',
          name: 'Rooftop Terrace Suite',
          description: 'Luxurious suite with access to rooftop restaurant and terrace.',
          images: ['https://picsum.photos/800/600?random=62', 'https://picsum.photos/800/600?random=63'],
          maxGuests: 2,
          pricePerNight: 320.0,
          isAvailable: false,
        ),
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        padding: const EdgeInsets.symmetric(vertical: 8),
        itemCount: _hotels.length,
        itemBuilder: (context, index) {
          final hotel = _hotels[index];
          return HotelCard(
            hotel: hotel,
            onViewRooms: () => onHotelTap?.call(hotel),
            onFavorite: () {

            },
            onTap: () => onHotelTap?.call(hotel),
          );
        },
      ),
    );
  }

}